# Generated by Django 4.1 on 2022-08-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='user',
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='email',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='aadhaar_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
