# Generated by Django 4.1 on 2022-08-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_extendeduser_user_extendeduser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
