# Generated by Django 4.1 on 2022-08-14 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_extendeduser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='username',
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
