# Generated by Django 4.1 on 2022-08-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_extendeduser_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='user',
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='email',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
